### PR TITLE
Update links, bio, avatars

### PR DESCRIPTION
**Pull request by melMass**

### CODE REVIEW

**Comment by melMass** [comment]
I will pick this PR up later today :)

**Comment by melMass** [comment]
image

**Comment by melMass** [comment]
@kylegrover I don't really understand the build setup with the mdx bundler and the next hot reload thing 😬 !
So I can't test it locally, as soon as I update the lock file for some strange reason.

So @merchantcoppola no urge for the merge, I will use the deploy URL on the beta site for now it's here:
https://deploy-preview-69--teia-blog.netlify.app/feed.xml

**Comment by melMass** [comment]
Rebased on main, removed extra stuff, I'll make a separate PR for that

**Comment by kylegrover** [comment]
amazin

**Pull request merged**
